/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('oranization').del()
  await knex('oranization').insert([
    {
      id: '56983724',
      name: '100 Hispanic Women National, Inc.',
      languages: 'English,Spanish',
      address: '413 E. 120th St. Suite 314 New York, NY 10035',
      phone: '(646) 689-2260',
      zipcode: '10035',
      description: 'Seeks to empower Latinas through personal and professional advancement initiatives, networks, and events.',
      link: 'https://www.100hispanicwomen.org/',
    },
    {
      id: '78462591',
      name: 'Advocates for Children of New York',
      languages: 'Arabic, Bengali, Chinese, English, French, Haitian Creole, Korean, Russian, Spanish, Urdu',
      address: '151 West 30th St. 5th Floor, New York, NY 10001',
      zipcode: '10001',
      phone: '(212) 947-9779',
      description: 'Seeks to promote access to the best education New York can provide for all students. Provides services with education specialists and attorneys for free legal counsel and representation at school-related hearings and appeals, and informative workshops and free resources.',
      link: 'http://www.advocatesforchildren.org/',
    },
    {
      id: '92651843',
      name: " African Communities Together",
      languages: "Amharic, Arabic, English, French, Fulani, Igbo, Krio, Kru, Mandingo, Yoruba, Wolof, and other African languages",
      address: "127 West 127th Street, Suite 221, New York, NY 10027",
      phone: "(347) 746-2281",
      zipcode: "10027",
      description: " general social work and service referral. Also, has interpreting services and advocacy.",
      link: "http://www.africans.us/",
    },
    {
      id: '28374961',
      name: "Alianza (Dominican Cultural Center)",
      languages: " English, Spanish",
      address: "530 West 166th Street at Amsterdam Avenue, New York, NY 10033",
      phone: "Phone: 212-740-1960",
      zipcode: "10033",
      description: "A non-profit community development organization that partners with youth, families and public and private institutions to revitalize economically distressed neighborhoods.",
      link: "www.harlemonestop.com/organization/748/alianza-dominicana-cultural-center",
    },
    {
      id: '65892317',
      name: "Asian Americans for Equality",
      languages: " English, Chinese, Mandarin, Cantonese, Spanish",
      address: "108 Norfolk Street, New York, NY 10002",
      phone: "212-979-8381",
      zipcode: "10002",
      description: "An organization committed to preserving affordable housing throughout New York and to providing counseling services, financial assistance and training to empower people, small businesses and neighborhoods.",
      link: "aafe.org",
    },
    {
      id: '42781659',
      name: "ASPIRA of New York",
      languages: "English, Spanish",
      address: "15 W. 36th St. 15th Floor, New York, NY 10018",
      phone: "(212) 564-6880",
      zipcode: "10018",
      description: "Advocates for and provides programs for the education and development of Latino and Puerto Rican youth in New York City. Programs relate to graduation, college access, skill development, community service, and other enrichment activities.",
      link: "http://www.aspirany.org/",
    },
    {
      id: '29354618',
      name: "Catholic Charities Archdiocese of New York",
      languages: " English, Spanish",
      address: "1011 First Avenue, 11th Floor, New York, NY 10022",
      phone: "(888) 744-7900",
      zipcode: "10022",
      description: "Provides services for children, the homeless and hungry, families, individuals with disabilities, and assist with crisis resolution and immigrant and refugee integration through legal counseling, English and civics classes, and work authorization.",
      link: "https://catholiccharitiesny.org/",
    },
    {
      id: '81573942',
      name: "Chinese Progressive Association",
      languages: "Chinese, English",
      address: "230 Grand St., New York, NY 10013",
      phone: "(212) 274-1891",
      zipcode: "10013",
      description: "Helps Chinese immigrants through English and citizenship classes, outreach and education, political empowerment, and information and referrals.",
      link: "https://www.cpanyc.info/",
    },
    {
      id: '47185923',
      name: "City Bar Justice Center",
      languages: "Has access to interpretation services for any language",
      address: "42 West 44th St., New York, NY 10036",
      phone: "(212) 382-6727",
      zipcode: "10036",
      description: "Offers access to legal services for low-income and disadvantaged New Yorkers in areas such as victims of violence, visas for immigrant victims of human trafficking, asylum representation, Deferred Action for Childhood Arrivals (DACA) and other forms of immigration relief.",
      link: "https://www.citybarjusticecenter.org/",
    },
    {
      id: '63912875',
      name: " CUNY Citizenship Now!",
      languages: "Cantonese, English, French, Haitian Creole, Korean, Italian, Mandarin, Polish, Spanish",
      address: "Various locations",
      phone: "(646) 664-9400",
      zipcode: "N/A",
      description: "University-based legal assistance program that provides free, high quality, and confidential citizenship and immigration law services to New Yorkers. Also hosts community, educational, and volunteer initiatives.",
      link: "http://www1.cuny.edu/sites/citizenship-now/",
    },
    {
      id: '18543796',
      name: "Damayan Migrant Workers Association",
      languages: " English, Tagalog",
      address: "406 West 40th St. 3rd Floor, New York, NY 10018",
      phone: "(212) 564-6057",
      zipcode: "10018",
      description: "Helps labor trafficking survivors develop escape plans, secure emergency housing and financial assistance, access social and legal services, find employment, and facilitate family reunifications. Also engages in community and organizing for fair labor standards and labor trafficking.",
      link: "https://www.damayanmigrants.org/",
    },
    {
      id: '56283914',
      name: "The Door",
      languages: "English, French, Haitian Creole, Spanish",
      address: "121 Avenue of the Americas, New York, NY 10013",
      phone: "(212) 941-9090",
      zipcode: "10013",
      description: "Provides young people with services in reproductive health care, mental health counseling, legal assistance, GED and English classes, college preparation, career development, supportive housing, recreational activities, and meals.",
      link: "https://www.door.org/",
    },
    {
      id: '34758621',
      name: "Families for Freedom",
      languages: "English, Spanish",
      address: "35 West 31th St #702, New York, NY 10001",
      phone: "(646) 290-8720",
      zipcode: "10001",
      description: "This is a multi-ethnic human rights organization by and for families facing and fighting deportation.",
      link: "www.familiesforfreedom.org",
    },
    {
      id: '97162348',
      name: "Flanbwayan Haitian Literacy Project",
      languages: "English, Haitian Creole",
      address: "208 Parkside Ave. 2nd Floor, Brooklyn, NY 11226",
      phone: "(718) 774-3037",
      zipcode: "11226",
      description: "Seeks to empower Haitian immigrant students in New York City, primarily English Language Learners, in their education. Provides advocacy services in school placement for newcomer youth and leadership and cultural events.",
      link: "http://www.flanbwayan.org/",
    },
    {
      id: '83419567',
      name: "HANAC",
      languages: "English, Greek",
      address: "27-40 Hoyt Ave. S, Astoria, New York 11102",
      phone: "(212) 840-8005",
      zipcode: "11102",
      description: "A social services organization that provides adult services such as legal help, training and employment, housing and counseling, arts programs, community building, early childhood education, mental health services, and youth development and education.",
      link: "http://hanac.org/",
    },
    {
      id: '24689371',
      name: "Her Justice",
      languages: "Arabic, English, French, Hindi, Italian, Korean, Romanian, Russian, Spanish, Urdu",
      address: "100 Broadway 10th Floor, New York, NY 10005",
      phone: "(212) 695-3800",
      zipcode: "10005",
      description: "Provides legal and social services to New York City women living in poverty in family court issues, divorce, and immigration. Does legal counseling, brief services, and free volunteer attorney representation.",
      link: "https://herjustice.org/",
    },
    {
      id: '51349876',
      name: "Immigrant Defense Project",
      languages: "English, Spanish",
      address: "40 West 39th St., 5th Floor, New York, NY 10018",
      phone: "(212) 725-6422",
      zipcode: "10018",
      description: "Uses impact litigation, advocacy, and public education to fight to stop mass deportations and an unjust immigration system.",
      link: "www.immigrantdefenseproject.org/",
    },
    {
      id: '72946581',
      name: "Immigrant Justice Corps",
      languages: "Arabic, Cantonese, Czech, French, Haitian Creole, Korean, Mandarin, Polish, Punjabi, Soninke, Spanish, Turkish, Urdu",
      address: "17 Battery Pl #1234, New York, NY 10004",
      phone: "(212) 407-3417",
      zipcode: "10004",
      description: "https://tinyurl.com/ijcwaitinglist",
      link: "https://tinyurl.com/ijcwaitinglist",
    },
    {
      id: '14836527',
      name: "Indochina Sino American Community Center",
      languages: "Cambodian, Cantonese, English, Fujianese, Lao, Mandarin, Vietnamese",
      address: "170 Forsyth St. 2nd Floor, New York, NY 10002",
      phone: "(212) 226-0317",
      zipcode: "10002",
      description: "Offers services to people from Vietnam, Cambodia, Laos, Hong Kong, Taiwan, Mainland China, and other parts of Southeast Asia. Offers immigrant and naturalization services, computer training, senior services, health services, English education, free food services, storage rooms, and a Buddhist sanctuary.",
      link: "http://www.isacc-ny.org/",
    },
    {
      id: '38671954',
      name: "International Refugee Assistance Project",
      languages: "English, Spanish, French",
      address: "40 Rector Street, 9th Floor, New York, NY 10006",
      phone: "(646) 602-5600",
      zipcode: "10006",
      description: "The International Refugee Assistance Project works to organize lawyers and law students to fight for the human and legal rights of refugees through legal aid and policy advocacy.",
      link: "www.refugeerights.org",
    },
    {
      id: '63982741',
      name: "International Rescue Committee",
      languages: "Has access to interpretation services for any language",
      address: "122 East 42nd Street, New York, New York 10168",
      phone: "(212) 551 - 3000",
      zipcode: "10168",
      description: "Helps people whose lives and livelihoods are shattered by conflict and disaster to survive, recover and regain control of their future.",
      link: "www.rescue.org",
    },
    {
      id: '27519836',
      name: "Kids in Need of Defense",
      languages: "English, Spanish",
      address: "N/A",
      phone: " (202) 824-8680",
      zipcode: "N/A",
      description: "Kids in Need of Defense staff and pro bono attorney partners at law firms, corporations, and law schools nationwide represent unaccompanied immigrant and refugee children in their deportation proceedings. Together, we ensure that no child stands in court alone.",
      link: "https://supportkind.org/",
    },
    {
      id: '71835692',
      name: "The Legal Aid Society",
      languages: "Has access to interpretation services for any language",
      address: "Multiple Locations",
      phone: "(212) 577-3300",
      zipcode: "N/A",
      description: "Provides individuals with legal assistance and advice in civil, criminal, and juvenile rights matters. Operates hotlines in immigration, access to benefits, homelessness, and low- income taxpayer, and has multiple locations.",
      link: "https://www.legalaidnyc.org/",
    },
    {
      id: '92471856',
      name: "Legal Services NYC",
      languages: "Cantonese, English, French, Haitian-Creole, Mandarin, Spanish, and others",
      address: "Multiple Locations",
      phone: "(646) 442-3600",
      zipcode: "",
      description: "Provides accessible legal services in a variety of areas, such as education, bankruptcy, civil rights and language access, consumer rights, disability, disaster recovery, employment law, family law, homeowner rights, government benefits, immigration, and LGBTQ advocacy.",
      link: "http://www.legalservicesnyc.org/",
    },
    {
      id: '56189327',
      name: "New York Legal Assistance Group",
      languages: "English, Mandarin, Russian, Spanish; interpretation services available as necessary",
      address: "7 Hanover Square 18th Floor, New York, NY 10004",
      phone: "(212) 613-5000",
      zipcode: "10004",
      description: "Addresses legal needs with comprehensive, free civil legal services in areas such as education, family, housing, employment, public benefits, immigration, and health.",
      link: "http://www.nylag.org/",
    },
    {
      id: '37891426',
      name: "Queer Detainee Empowerment Project",
      languages: "English, French, Polish, Spanish",
      address: "505 8th Ave. #1212, New York, NY 10018",
      phone: "(347) 645-9339",
      zipcode: "10018",
      description: "Assists LGBTQIA GNC & TS individuals coming out of immigration detention in securing social supports and services.",
      link: "http://www.qdep.org/",
    },
    {
      d: '91628437',
      name: " Restaurant Opportunities Centers United",
      languages: "Arabic, English, French, Spanish, and others",
      address: "275 Seventh Ave. Suite 1703, New York, NY 10001",
      phone: "(212) 343-1771",
      zipcode: "10001",
      description: "Seeks to improve wages and working conditions for the nation’s restaurant workforce. Does restaurant job training and placement, leadership development, legal support, and policy advocacy.",
      link: "http://rocunited.org/",
    },
    {
      id: '48731695',
      name: "Safe Horizon Immigration Law Project",
      languages: " English, Spanish",
      address: "50 Court St. 8th Floor, Brooklyn, NY 11201",
      phone: "(718) 943-8632",
      zipcode: "10033",
      description: "A victim assistance nonprofit that provides assistance, advocacy, and legal service support to immigrant victims of domestic violence, child abuse, sexual assault, stalking, human trafficking, youth homelessness, and other crimes.",
      link: "https://www.safehorizon.org/",
    },
    {
      id: '36287145',
      name: "Safe Passage Project",
      languages: "English, French, Spanish; access to volunteer interpreters who speak a variety of languages",
      address: "185 West Broadway, New York, NY 10013",
      phone: "(212) 324-6558",
      zipcode: "10013",
      description: "Works with volunteer attorneys and law school students to provide representation of unaccompanied minors in the immigration process.",
      link: "https://www.safepassageproject.org/",
    },
    {
      id: '72964318',
      name: ". Sakhi for South Asian Women",
      languages: "Bengali, English, Hindi, Malayalam, Marathi, Punjabi, Tamil, Urdu",
      address: "P.O. Box 1333, Church Street Station, New York, NY 10008",
      phone: "(212) 714-9153",
      zipcode: "10008",
      description: "Seeks to end violence against women from the South Asian Diaspora through domestic violence & sexual assault services, an economic empowerment program, immigration & civic integration, reproductive justice, a youth empowerment program, and outreach, workshops and trainings.",
      link: "http://www.sakhi.org/",
    },
    {
      id: '81769345',
      name: "UnLocal, Inc.",
      languages: "English, Spanish",
      address: "45 W. 29th St. Suite 203 New York, NY 10001",
      phone: " (646) 216-8210",
      zipcode: "10001",
      description: "Connects immigrants with affordable, trustworthy, comprehensive, and multilingual legal representation and case management. Also provides immigration information and develops community projects based on need.",
      link: "http://www.unlocal.org/",

    },
    {
      id: '39428716',
      name: "Urban Justice Center",
      languages: "Has access to interpretation services for any language",
      address: "40 Rector St. , 9th Fl. New York, NY 10006",
      phone: "(646) 602-5600",
      zipcode: "10006",
      description: "Provides programs in direct legal services, advocacy, community education, and political organizing to New York City residents. Populations served include asylum seekers, refugees, and other vulnerable groups",
      link: "https://www.urbanjustice.org/",

    },
    {
      id: '64513978',
      name: "Violence Intervention Program, Inc.",
      languages: "English, Spanish; has access to interpretation services for most languages",
      address: "Triborough Station, P.O. Box 1161, New York, NY 10035",
      phone: " (800) 664-5880",
      zipcode: "10035",
      description: "Provides services to victims of domestic violence, including those with undocumented status. Has programs in immigration, counseling, housing, economic justice, language access, and other trainings and workshops.",
      link: "https://www.vipmujeres.org/",

    },
    {
      id: '15837426',
      name: "Community Association of Progressive Dominicans",
      languages: "English, Spanish",
      address: "3940 Broadway, New York, NY 10032",
      phone: " (212) 781-5500",
      zipcode: "10032",
      description: "Provides services to New York’s Dominican immigrants and their communities. Offers education and youth development programs, such as college access, career development, afterschool programs, mental health services, adult literacy, and English classes.",
      link: "http://www.acdp.org/",

    },
    {
      id: '49278613',
      name: "Masa-MexEd, Inc.",
      languages: "English, Spanish",
      address: "2770 Third Ave. 1st Floor, Bronx, NY 10455",
      phone: "(646) 481-5890",
      zipcode: "10455",
      description: "Serves Mexican and Latino individuals in the South Bronx with early childhood education programs, afterschool and extracurricular programs for youth, civic engagement workshops, family support, case management, legal services in immigration, and community leadership initiatives.",
      link: "http://masany.org/",
    },
    {
      id: '76132984',
      name: "Mercy Center, Inc.",
      languages: "English, Spanish",
      address: "377 E. 145th St., Bronx, NY 10454",
      phone: "(718) 993-2789",
      zipcode: "10454",
      description: "Empowers women and their families in the South Bronx through services such as counseling, parenting classes and support groups, family development, domestic violence support, career development, English classes and immigrant services, and youth programs.",
      link: "https://www.mercycenterbronx.org/",
    },
    {
      id: '93518467',
      name: "Sauti Yetu Center for African Women and Families",
      languages: " Arabic, English, French, Fulani, Kotokoli, Mandingo, Soninke, Susu, Twi, Wolof, and other African languages",
      address: "2417 3rd Ave.Suite 205, Bronx, NY 10451",
      phone: "(718) 665-2486",
      zipcode: "10451",
      description: "Provides services for poor and low- income African immigrant women and families.Includes social services support, awareness workshops and information on female genital cutting, services in domestic & sexual violence, programs in supportive counseling, and an immigrant youth program.",
      link: "http://www.sautiyetu.us/",

    },
    {
      id: '27891634',
      name: "St. Jerome H.A.N.D.S. Community Center",
      languages: "English, Spanish",
      address: "330 E. 138th St., Bronx, NY 10454",
      phone: "(718) 402-7866",
      zipcode: "10454",
      description: "Offers education and social services to families and immigrants with classes in English, computer literacy, citizenship, and GED. Also provides food services and job security assistance.",
      link: "https://www.jeromehands.com/",

    },
    {
      id: '86429315',
      name: "Academy of Medical and Public Health Services",
      languages: "Arabic, Burmese, Cantonese, English, French, Indonesian, Mandarin, Spanish",
      address: "5306 Third Ave. Second Floor, Brooklyn, NY 11220",
      phone: "(212) 256-9036",
      zipcode: "11220",
      description: "Offers free and accessible care to immigrant New Yorkers, including clinical services, social services referrals and information, and training and education to those interested in the healthcare professions field.",
      link: "http://www.amphsonline.org/",

    },
    {
      id: '17268439',
      name: "Arab-American Family Support Center",
      languages: "Arabic, Bengali, English, Farsi, French, Hindi, Pashto, Punjabi, Nepali, Spanish, Tibetan, Urdu, Wakhi, and various dialects",
      address: "150 Court St. 3rd Floor, Brooklyn, NY 11201",
      phone: " (718) 643-8000",
      zipcode: "11201",
      description: "Offers programs for immigrants in preventive services, health care access, adult education and literacy, legal assistance, youth development, and anti-violence.",
      link: "https://aafscny.org/",
    },
    {
      id: '52763148',
      name: "Catholic Migration Services",
      languages: "Has access to interpretation in any language",
      address: "191 Joralemon St. 4th Floor, Brooklyn, NY 11201",
      phone: "(718) 236-3000",
      zipcode: "11201",
      description: "Offers assistance to immigrants in immigration legal services, housing legal services, and immigrant workers’ rights legal services, regardless of religious background.",
      link: "https://catholicmigration.org/",
    },
    {
      id: '34918526',
      name: "Central American Legal Assistance",
      languages: "English, French, Spanish",
      address: "240 Hooper St., Brooklyn, NY 11211",
      phone: "(718) 486-6800",
      zipcode: "11211",
      description: "Provides free or low-cost legal services to Central and South American asylum-seekers in Brooklyn.",
      link: "https://www.centralamericanlegal.info",
    },
    {
      id: '98651247',
      name: "Family Health Centers at NYU Langone",
      languages: "Arabic, Chinese, English, Russian, Spanish",
      address: "Multiple Locations",
      phone: "(718) 630-7942",
      zipcode: "N/A",
      description: "Provides quality primary and preventive outpatient care to individuals, regardless of ability to pay or health insurance status. Many Brooklyn sites.",
      link: "https://nyulangone.org/locations/family-health-centers-at-nyu-langone",
    },
    {
      id: '71589632',
      name: "Flanbwayan Haitian Literacy Project",
      languages: "English, Haitian Creole, French",
      address: "208 Parkside Avenue, 2nd Floor, Brooklyn, NY 11226",
      phone: " (718) 774-3037",
      zipcode: "11226",
      description: "This organization serves newcomer and young adult Haitian immigrant students in New York City who are English Language Learners (ELLs) between the ages of 14 to 21.",
      link: "flanbwayan.org",
    },
    {
      id: '26189375',
      name: "Make the Road NY",
      languages: "English, Spanish",
      address: "301 Grove Street, Brooklyn, NY 11237",
      phone: "(718) 418-7690",
      zipcode: "11237",
      description: "Make the Road New York builds the power of Latino and working-class communities to achieve dignity and justice through organizing, policy innovation, transformative education, and survival services.",
      link: "www.maketheroadny.org",

    },
    {
      id: '59836714',
      name: "Mixteca Organization",
      languages: " English, Spanish",
      address: "245 23rd St. 2nd Floor, Brooklyn, New York 11215",
      phone: "(718) 965-4795",
      zipcode: "11215",
      description: "Offer programs and services for the Mexican and Latin American immigrant communities in Brooklyn and New York. Programs in adult education, health, domestic violence services, HIV/AIDS services, and immigration legal services.",
      link: "http://www.mixteca.org",
    },
    {
      id: '43781926',
      name: "Opportunities for a Better Tomorrow",
      languages: "English, Spanish",
      address: "Multiple Locations",
      phone: " (718) 369-0303",
      zipcode: "N/A",
      description: "Offers job training and support services to young adults, adults, and immigrants. Includes job training, job placement assistance, GED classes, and English classes as well as legal services for immigrants.",
      link: "https://obtjobs.org/",
    },
    {
      id: '91653827',
      name: "Northern Manhattan Coalition for Immigrant Rights",
      languages: "English, French, Spanish",
      address: "665 West 182nd Street, Ground Floor, New York, NY 10033",
      phone: "10033",
      zipcode: "10033",
      description: "Is committed to expanding access to legal immigration services, participating in policy making and community organizing.Educates, defends and protects the rights of immigrants.",
      link: "nmcir.org",
    },
    {
      id: '67451829',
      name: "Northern Manhattan Improvement Corporation",
      languages: "English, Spanish",
      address: "45 Wadsworth Ave., New York, NY 10033",
      phone: "(212) 822-8300",
      zipcode: "10033",
      description: "Provides comprehensive services in crisis intervention, legal services, safety planning, immigration services, mental health counseling, language interpretation, public benefits, job training, eviction prevention, access to healthcare, and adult education.",
      link: "http://www.nmic.org/",
    },
    {
      id: '13596824',
      name: "Adhikaar",
      languages: "English, Hindi, Nepali, Tibetan",
      address: "71-07 Woodside Ave. 1st Floor, Woodside, NY 11377",
      phone: "(718) 937-1117",
      zipcode: "11377",
      description: "A service and advocacy organization for the Nepali-speaking community that provides direct services such as translation and interpretation for Nepali and Tibet",
      link: "http://www.adhikaar.org/",
    },
    {
      id: '24871693',
      name: "Arab-American Family Support Center",
      languages: " Arabic, Bengali, English, Farsi, French, Hindi, Pashto, Punjabi, Nepali, Spanish, Tibetan, Urdu, Wakhi, and various dialects",
      address: "37-10 30th St. 2nd Floor, Queens, NY 11101",
      phone: "(718) 937-8000",
      zipcode: "11101",
      description: "Offers programs for immigrants in preventive services, health care access, adult education and literacy, legal assistance, youth development, and anti-violence.",
      link: "https://aafscny.org/",
    },
    {
      id: '36589127',
      name: "CAIR-NY Council on American-Islamic Relations",
      languages: "English, Arabic, Urdu",
      address: "46-01 20th Avenue, Astoria, NY, 11105",
      phone: " (646) 665-7599",
      zipcode: "11105",
      description: "The Council on American-Islamic Relations-NY (CAIR) is one of the largest civil rights and advocacy organizations dedicated to fighting against discrimination against Muslims.",
      link: "www.cair-ny.org/",
    },
    {
      id: '81943765',
      name: "Catholic Migration Services",
      languages: "Has access to interpretation in any language",
      address: "47-01 Queens Boulevard Suite 201, Sunnyside, NY 11104",
      phone: "(347) 472-3500",
      zipcode: "11104",
      description: "Offers assistance to immigrants in immigration legal services, housing legal services, and immigrant workers’ rights legal services, regardless of religious background.",
      link: "https://catholicmigration.org/",
    },
    {
      id: '47295618',
      name: "Center for the Integration and Advancement of New Americans",
      languages: "Arabic, Bengali, English, French, German, Hindi, Italian, Punjabi, Spanish, Turkish, Urdu, and other languages",
      address: "31-09 Newtown Ave. Suite 411, Astoria, NY 11102",
      phone: "(718) 545-4040",
      zipcode: "11102",
      description: "Offers services for immigrants including adult English and citizenship classes, legal services, tutoring and afterschool programs for youth, career services, and case management.",
      link: "https://www.cianainc.org/",
    },
    {
      id: '68723159',
      name: "Desis Rising Up & Moving",
      languages: "English, Portuguese, Spanish",
      address: "31-09 Newtown Ave. Suite 411, Astoria, NY 11102",
      phone: "(718) 545-4040",
      zipcode: "11102",
      description: "Offers services for immigrants including adult English and citizenship classes, legal services, tutoring and afterschool programs for youth, career services, and case management.",
      link: "https://www.cianainc.org/",
    },
    {
      id: '35968241',
      name: "Emerald Isle Immigration Center",
      languages: "English, Spanish",
      address: "59-26 Woodside Ave., Woodside, NY 11377",
      phone: "(718) 478-5502",
      zipcode: "11377",
      description: "Provides immigration information, social services assistance in public assistance, senior services, healthcare, mental health, and education and employment referrals and workshops.",
      link: "http://eiic.org/",
    },
    {
      id: '54619723',
      name: "Immigration Advocacy Services, Inc.",
      languages: " Arabic, English, Greek, Hindi, Italian, Punjabi, Portuguese, Russian, Spanish, Urdu",
      address: "36-16 Astoria Blvd. South, Astoria, NY 11103",
      phone: "(718) 956-8218",
      zipcode: "11103",
      description: "Offers services for immigrants including adult English and citizenship classes, legal services, tutoring and afterschool programs for youth, career services, and case management.",
      link: "https://www.cianainc.org/",
    },
    {
      id: '91528347',
      name: " Jacob A. Riis Neighborhood Settlement",
      languages: "Bengali, English, French, Greek, Haitian Creole, Hindi, Italian, Mandarin, Russian, Spanish, and other languages",
      address: "10-25 41st Ave., Long Island City, NY 11101",
      phone: "(718) 784-7447",
      zipcode: "11101",
      description: "Offers immigrant services in western Queens, such as English classes, support services, and community building activities, as well as general youth and senior programs.",
      link: "http://www.riissettlement.org/",
    },
    {
      id: '57396418',
      name: "Latin Women in Action, Inc.",
      languages: "Chinese, English, Portuguese, Spanish",
      address: "103-06 39 Ave., Corona, NY 11368",
      phone: "(718) 478-2972",
      zipcode: "11368",
      description: "Seeks to empower Latina women and their families through domestic violence and child abuse prevention, political empowerment, civic engagement, and direct services in immigration, health, employment, counseling, and others.",
      link: "http://www.latinwomeninaction.com/",
    },
    {
      id: '71263849',
      name: "MinKwon Center for Community Action, Inc.",
      languages: "Chinese, English, Korean",
      address: "136-19 41st Ave. 3rd Floor, Flushing, NY 11355",
      phone: "(718) 460-5600",
      zipcode: "11355",
      description: "Advocates for Korean American and Asian American immigrant communities through community organizing, civic participation initiatives, cultural events, and youth development. Also offers social and legal services in immigration, tenants’ rights, workers’ rights, and public assistance.",
      link: "http://minkwon.org/",

    },
    {
      id: '65934812',
      name: "New Immigrant Community Empowerment(NICE)",
      languages: "English, Spanish",
      address: "71 - 29 Roosevelt Avenue, 2nd Floor, Queens, NY 11273",
      phone: "(718) 205 - 1687",
      zipcode: "11273",
      description: "Provides critical services and resources to prevent worker exploitation and ensure workers' safety and rights are respected. Most importantly, empowers workers to organize around key issues that impact the community to change the systemic injustices immigrant workers face. Creates pathways to success and empowerment for essential immigrant workers.",
      link: "https://nynice.squarespace.com/",
    },
    {
      id: '13827549',
      name: "Polonians Organized to Minister to Our Community",
      languages: "English, Polish",
      address: "6660 Fresh Pond Road, Ridgewood, NY 11385",
      phone: "(718) 366-5365",
      zipcode: "11385",
      description: "Assists Polish immigrants in filing for government entitlements, job referrals, English classes, and emergency assistance in food and clothing.",
      link: "http://pomocny.org/",
    },
    {
      id: '48756239',
      name: " Queens Community House",
      languages: "English, Hindi, Mandarin, Russian, Spanish",
      address: "108 - 25 62nd Drive, Queens, NY 11375",
      phone: "(718) 592 - 5757",
      zipcode: "11375",
      description: "Has 29 sites in Queens that provide youth development programming, housing and homeless prevention services, food access initiatives, immigrant services including English classes and legal assistance, and senior programs.",
      link: "https://www.qchnyc.org/",
    },
    {
      id: '72619348',
      name: "Women for Afghan Women New York Community Center",
      languages: " Dari, English, Pashto",
      address: "71 - 19 162nd St.Unit CF - D, Fresh Meadows, NY 11365",
      phone: "(718) 591 - 2434",
      zipcode: "11365",
      description: "Provides supports and services for Afghan women including case management counseling, immigration assistance, housing, public benefits, education and classes, employment, health, domestic violence services, wellness workshops, a girls’ leadership program, and a support group.",
      link: "http://www.womenforafghanwomen.org/",
    },
    {
      id: '91467382',
      name: "YWCA Queens",
      languages: "English, Chinese, Korean, Spanish",
      address: "42 - 07 Parsons Blvd., Flushing, NY 11355",
      phone: "(718) 353 - 4553",
      zipcode: "11355",
      description: "Provides services to women and families in Queens through programs addressing economic empowerment, racial justice, women’s health, family support, employment assistance, workshops, and immigration services.",
      link: "http://ywcaqueens.org/",
    },
    {
      id: '75842931',
      name: "El Centro del Inmigrante",
      languages: "English, Spanish",
      address: "1546 Castleton Ave., Staten Island, NY 10302",
      phone: "(718) 825 - 2086",
      zipcode: "10302",
      description: "Provides services to Staten Island immigrants primarily from Mexico and Latin America.Includes English, GED, and literacy classes, labor organizing, health education and screenings, family and immigrant rights services, legal assistance, community activities, and food and clothing distribution.",
      link: "http://elcentronyc.org/",
    },
    {
      id: '08364821',
      name: "Migration Resource Center Staten Island",
      languages: "Albanian, Dutch, English, French, Greek, Italian, Spanish",
      address: "36 Richmond Terrace Suite 307, Staten Island, NY 10301",
      phone: "(646) 609 - 8805",
      zipcode: "10301",
      description: "Offers immigration legal services, English and citizenship education and classes, community outreach programs, and fundraising for the low - income immigrant community.",
      link: "http://www.migrationusa.org/",
    },
    {
      id: '20864297',
      name: "Sauti Yetu Center for African Women and Families",
      languages: "Arabic, English, French, Fulani, Kotokoli, Mandingo, Soninke, Susu, Twi, Wolof, and other African languages",
      address: "380 - 384 Van Duzer St. 1st Floor, Staten Island, NY 10304",
      phone: "(718) 665 - 2486 ",
      zipcode: "10304",
      description: 'Provides services for poor and low-income African immigrant women and families. Includes social services support, awareness workshops and information on female genital cutting, services in domestic & sexual violence, programs in supportive counseling, and an immigrant youth program.',
      link: "http://www.sautiyetu.us/",
    },

  ]);
};
